language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=^9 FUNCTIONALS=1
    - php: 7.3
      env: TYPO3_VERSION=^9 FUNCTIONALS=1
    - php: 7.4
      env: TYPO3_VERSION=^9 FUNCTIONALS=1

services:
  - mysql

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - breakpoint@schreibersebastian.de

before_install:
  - composer self-update
  - composer --version

before_script:
  - phpenv config-rm xdebug.ini
  - composer require "typo3/minimal:${TYPO3_VERSION}"
  # Restore composer.json
  - git checkout composer.json

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/vendor/bin/phpunit --colors -c Tests/Build/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    .Build/vendor/bin/phpunit --colors -c Tests/Build/FunctionalTests.xml Tests/Functional/
