version: '3.6'

services:
    web:
        environment:
            - TZ=Europe/Berlin
            - TYPO3_CONTEXT=Development
            - typo3DatabaseHost=db
            - typo3DatabaseName=t3func
            - typo3DatabasePassword=root
            - typo3DatabaseUsername=root
    db:
        environment:
            - TZ=Europe/Berlin
