---
name: CI

on: [ push, pull_request ]

jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: [ 7.3, 7.4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-versions }}"
      - name: "Cache composer dependencies"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}
            -composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-versions }}-composer-
      - name: "Install composer dependencies"
        run: composer install --no-progress --no-suggest
      - name: "Run PHP lint"
        run: composer run-script test-php-lint
  php-cs-fixer:
    name: "PHP-CS-Fixer"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: [ 7.3, 7.4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-versions }}"
      - name: "Cache composer dependencies"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}
            -composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-versions }}-composer-
      - name: "Install composer dependencies"
        run: composer install --no-progress --no-suggest
      - name: "Run PHP-CS-Fixer"
        run: "composer run-script test-php-cs-fixer"
  tests:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 2
      matrix:
        php-versions: [ 7.3, 7.4 ]
        typo3-versions:
          - { typo3: 9 }
          - { typo3: 10 }
    name: "Run tests with PHP ${{ matrix.php-versions }}"
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring, pdo_sqlite, pdo_mysql

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: "Cache composer dependencies"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}
            -typo3-${{ matrix.typo3-versions.typo3 }}
            -composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-versions }}
            -typo3-${{ matrix.typo3-versions.typo3 }}
            php-${{ matrix.php-versions }}-typo3-

      - name: "Install composer dependencies"
        run: composer install --no-progress --no-suggest

      - name: "Functional tests"
        run: |
          export typo3DatabaseName="typo3";
          export typo3DatabaseHost="127.0.0.1";
          export typo3DatabaseUsername="root";
          export typo3DatabasePassword="root";
          composer run-script test-functional
